### ISSUE TITLE
rerender on changing the length of tbody

### ISSUE THREAD

**Issue by farahamawi** [addhome2001/react-pagination-table#13]
Hi ,
I'm using react-pagination-table and I implement a filter on the table data but once I got the result of the filter (changing the length of table data from 40 to 2 for example) the number of the pagination pages does not rerender, it displays 9 pages although I only need one page to display my 2 values after filter
although the total count changes but no reflect on the number of pages
My initial guess is that you are using the totalCount props inside componentDidMount so it will take the initial value first but on recieving new props it will not rerender

**Comment by rajatpillai** [comment]
I am facing the same issue @farahamawi did you get any solution for this.

**Comment by rajatpillai** [comment]
Hey @farahamawi I have resolved this issue by adding key={data.length} into it 

Example:-

` <TablePagination`
              `  title="TablePagination"`
             `   subTitle="Sub Title"`
             `   headers={ Header }`
             `   data={ data }`
             `   columns="name.age.size.phone.gender"`
            `   perPageItemCount={ 5 }`
           `   totalCount={ data.length }`
            `  arrayOption={ [["size", 'all', ' ']] }`
           `   key={ data.length }`
       ` />`

**Comment by farahamawi** [comment]
Thank you @rajatpillai  it worked for me, I'll close this issue.
