### ISSUE TITLE
NextPageText and prePageText cannot be changed

### ISSUE THREAD

**Issue by dhentschel06** [addhome2001/react-pagination-table#2]
Hi @addhome2001 
thank you for this component.
Unfortunatly it seems that the Pagination.defaultProps are always used.
```javascript
<TablePagination
      title="TablePagination"
      subTitle="Sub Title"
      headers={ Header }
      data={ data }
      columns="name.age.size.phone.gender"
      perPageItemCount={ 5 }
      totalCount={ data.length }
      arrayOption={ ['size', 'all', ' '] }
      nextPageText="Change ME to Next"
      prePageText="Change ME to Prev"
/>
``` 
Is there a quick fix for this?

**Comment by addhome2001** [comment]
It was remiss of me not to answer your question.
I have repaired the issue in the newer version `1.0.3`, you can try to reinstall the package again.

Thank you for your feedback.😊🙏
