### ISSUE TITLE
Format of Data

### ISSUE THREAD

**Issue by esend7881** [addhome2001/react-pagination-table#3]
Hello,
I have a table which contains state-ful data, including select/options which can update depending on the backend server or client.

Will your `data` object be able to take in more than just strings?

It would be good to know before if this feature is there or if I'd need to flesh it out, etc.

Thanks

**Comment by addhome2001** [comment]
Hi, thank you for your feedback, propTypes of `data` expect array of object, it's regardless of the object's type.
I think you may need to warp the `state-ful` data in a component before passing to the `react-pagination-table`.
```js
const defaultData = [
    { size: ['L', 'M'], nums: ['num1', 'num2', 'num3', 'num4'], gender: 'Male', age: 20, name: 'Ben' },
    { size: ['L', 'M', 'XL'], nums: ['num1', 'num2', 'num3', 'num4'], gender: 'Female', age: 22, name: 'Ken' },
    { size: ['L', 'S'], nums: ['num1', 'num2', 'num3', 'num4'], gender: 'Female', age: 23, name: 'Jay' },
];

```
a simple `select` component
```js
const NumComponent = ({ nums }) =>
  <select>
    {
      nums.map(num =>
        <option key={ num } value={ num }>{ num }</option>,
      )
    };
  </select>
```
transform the data before passing to the `react-pagination-table`
```js
const newData = defaultData.map(data => {
  return Object.assign({},
    data,
    { nums: <NumComponent nums={ data.nums } /> },
    // others `state-ful` components
  );
});
```
But, I recommend that you implement with [HOC](https://facebook.github.io/react/docs/higher-order-components.html).
Hope it makes sense. Let me know if you can figure it out.
