### ISSUE TITLE
keys not unique on table td's when repeating columns

### ISSUE THREAD

**Issue by gregsandell** [addhome2001/react-pagination-table#7]
Edge case...I wanted to have two columns with the same data, so I set the `columns` attribute to "id.url.url".  (My data consists of fields `id, url and source_url`. )  When I do that I get a non-unique keys warning:

proxyConsole.js:54 Warning: Encountered two children with the same key, `col-url`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

When I change `columns` to "id.url.source_url" problem goes away.

**Comment by addhome2001** [comment]
Sorry for my late reply.

In your situation, setting the columns attribute to "id.url.url", the last two columns will be the property of `url`(and the same render key). The fields of `columns` attribute will be taken as the render keys and the `key` within your data iteration. So if you set the `columns` to `id.url.source_url`, the last two columns will be unique and fit your expectation.

Hope it makes sense.

**Comment by uthayacloud** [comment]
Pagination count more than 5 or 6 etc.. then showing all Pagination
![screen shot 2018-03-21 at 11 48 33 am](https://user-images.githubusercontent.com/15226281/37693925-d2deff9e-2cfd-11e8-86b7-1c2fd3372376.png)

**Comment by uthayacloud** [comment]
Help me to fix this issue

**Comment by addhome2001** [comment]
Hi, @uthayacloud. I saw your issue recently. Sorry about that...
Actually, I know the feature is important to pagination. I will fix the issue very soon.

**Comment by addhome2001** [comment]
Hi, @uthayacloud,  I have released the v2.0 that will solve the issue described above.

Hope it will meet your expectations and I will close this issue.

**Comment by uthayacloud** [comment]
Thank you
